Repository team-express/velo9, pull requests merged in 2022-03, with the labels that each got.

#13 썸네일 crd 구현
  build.gradle
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/member/domain/Refer.java
  src/main/java/teamexpress/velo9/post/controller/PostThumbnailFileController.java
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/domain/PostTag.java
  src/main/java/teamexpress/velo9/post/domain/PostThumbnail.java
  src/main/java/teamexpress/velo9/post/domain/Series.java
  src/main/java/teamexpress/velo9/post/domain/Tag.java
  src/main/java/teamexpress/velo9/post/dto/PostThumbnailFileDTO.java
  src/main/java/teamexpress/velo9/post/service/PostThumbnailFileService.java
  src/main/resources/application.properties
Labels: feature, 글쓰기

#16 썸네일 비정상적인 사용 해결
  .gitignore
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/member/domain/MemberThumbnail.java
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/domain/PostThumbnail.java
  src/main/java/teamexpress/velo9/post/domain/PostThumbnailType.java
  src/main/java/teamexpress/velo9/post/service/PostThumbnailFileService.java
Labels: 글쓰기, bug

#21 feat: 회원가입 로직 구현
  .gitignore
  build.gradle
  src/main/java/teamexpress/velo9/AsyncConfig.java
  src/main/java/teamexpress/velo9/member/controller/MailController.java
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/member/domain/MemberRepository.java
  src/main/java/teamexpress/velo9/member/domain/Role.java
  src/main/java/teamexpress/velo9/member/dto/MailContentDTO.java
  src/main/java/teamexpress/velo9/member/dto/MailDTO.java
  src/main/java/teamexpress/velo9/member/dto/MemberSignupDTO.java
  src/main/java/teamexpress/velo9/member/security/configure/AjaxSecurityConfig.java
  src/main/java/teamexpress/velo9/member/service/MailHandler.java
  src/main/java/teamexpress/velo9/member/service/MailService.java
  src/main/java/teamexpress/velo9/member/service/MemberService.java
  src/main/resources/application.properties
Labels: feature, 회원가입

#23 Login
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/member/security/CustomUserDetailsService.java
  src/main/java/teamexpress/velo9/member/security/MemberContext.java
  src/main/java/teamexpress/velo9/member/security/common/AjaxLoginAuthenticationEntryPoint.java
  src/main/java/teamexpress/velo9/member/security/configure/AjaxLoginConfigurer.java
  src/main/java/teamexpress/velo9/member/security/configure/AjaxSecurityConfig.java
  src/main/java/teamexpress/velo9/member/security/filter/AjaxLoginProcessingFilter.java
  src/main/java/teamexpress/velo9/member/security/handler/AjaxAccessDeniedHandler.java
  src/main/java/teamexpress/velo9/member/security/handler/AjaxAuthenticationFailureHandler.java
  src/main/java/teamexpress/velo9/member/security/handler/AjaxAuthenticationSuccessHandler.java
  src/main/java/teamexpress/velo9/member/security/provider/AjaxAuthenticationProvider.java
  src/main/java/teamexpress/velo9/member/security/token/AjaxAuthenticationToken.java
Labels: feature, 로그인

#24 소셜 로그인 기능 구현
  build.gradle
  src/main/java/teamexpress/velo9/member/controller/MailController.java
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/member/security/configure/AjaxSecurityConfig.java
  src/main/java/teamexpress/velo9/member/security/oauth/CustomOAuth2UserService.java
  src/main/java/teamexpress/velo9/member/security/oauth/OAuthAttributes.java
  src/main/java/teamexpress/velo9/member/security/oauth/SessionConst.java
  src/main/java/teamexpress/velo9/member/service/MemberService.java
Labels: feature, 로그인, refactoring

#25 기본적인 글쓰기 구현
  .gitignore
  build.gradle
  src/main/java/teamexpress/velo9/Velo9Application.java
  src/main/java/teamexpress/velo9/common/domain/BaseEntity.java
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/member/domain/MemberRepository.java
  src/main/java/teamexpress/velo9/member/domain/MemberThumbnail.java
  src/main/java/teamexpress/velo9/member/domain/Refer.java
  src/main/java/teamexpress/velo9/member/domain/Role.java
  src/main/java/teamexpress/velo9/member/security/common/AjaxLoginAuthenticationEntryPoint.java
  src/main/java/teamexpress/velo9/member/security/configure/AjaxLoginConfigurer.java
  src/main/java/teamexpress/velo9/member/security/configure/AjaxSecurityConfig.java
  src/main/java/teamexpress/velo9/member/security/filter/AjaxLoginProcessingFilter.java
  src/main/java/teamexpress/velo9/member/security/handler/AjaxAccessDeniedHandler.java
  src/main/java/teamexpress/velo9/member/security/handler/AjaxAuthenticationFailureHandler.java
  src/main/java/teamexpress/velo9/member/security/handler/AjaxAuthenticationSuccessHandler.java
  src/main/java/teamexpress/velo9/member/security/oauth/OAuthAttributes.java
  src/main/java/teamexpress/velo9/member/security/oauth/SessionConst.java
  src/main/java/teamexpress/velo9/member/security/provider/AjaxAuthenticationProvider.java
  src/main/java/teamexpress/velo9/member/security/token/AjaxAuthenticationToken.java
  src/main/java/teamexpress/velo9/member/service/MailHandler.java
  src/main/java/teamexpress/velo9/member/service/MailService.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/controller/PostThumbnailFileController.java
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/domain/PostRepository.java
  src/main/java/teamexpress/velo9/post/domain/PostTag.java
  src/main/java/teamexpress/velo9/post/domain/PostThumbnail.java
  src/main/java/teamexpress/velo9/post/domain/PostThumbnailRepository.java
  src/main/java/teamexpress/velo9/post/domain/Series.java
  src/main/java/teamexpress/velo9/post/domain/Tag.java
  src/main/java/teamexpress/velo9/post/dto/PostSaveDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostThumbnailFileDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostThumbnailSaveDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/java/teamexpress/velo9/post/service/PostThumbnailFileService.java
  src/main/java/teamexpress/velo9/post/task/PostThumbnailTask.java
  src/main/resources/application-oauth.properties
  src/main/resources/application.properties
Labels: feature, 글쓰기

#27 Write
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/member/domain/MemberRepository.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/domain/PostAccess.java
  src/main/java/teamexpress/velo9/post/domain/PostStatus.java
  src/main/java/teamexpress/velo9/post/domain/PostTag.java
  src/main/java/teamexpress/velo9/post/domain/PostTagRepository.java
  src/main/java/teamexpress/velo9/post/domain/Series.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepository.java
  src/main/java/teamexpress/velo9/post/domain/Tag.java
  src/main/java/teamexpress/velo9/post/domain/TagRepository.java
  src/main/java/teamexpress/velo9/post/dto/PostSaveDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/java/teamexpress/velo9/post/service/TagService.java
Labels: feature, 글쓰기

#31 개인블로그 메인 - 시리즈 관련 글 보기 구현
  build.gradle
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/controller/PostThumbnailFileController.java
  src/main/java/teamexpress/velo9/post/domain/PostTag.java
  src/main/java/teamexpress/velo9/post/domain/Series.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepository.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/domain/Tag.java
  src/main/java/teamexpress/velo9/post/dto/PostSaveDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostSummaryDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostThumbnailDTO.java
  src/main/java/teamexpress/velo9/post/dto/SeriesDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/java/teamexpress/velo9/post/service/PostThumbnailFileService.java
  src/main/java/teamexpress/velo9/post/service/TagService.java
  src/main/resources/application.properties
Labels: feature, 개인블로그메인/시리즈

#33 소셜 회원 가입 시 썸네일 받아 저장하기 + Quartz라이브러리 적용
  src/main/java/teamexpress/velo9/member/api/MemberThumbnailFileUploader.java
  src/main/java/teamexpress/velo9/member/domain/MemberThumbnail.java
  src/main/java/teamexpress/velo9/member/domain/MemberThumbnailRepository.java
  src/main/java/teamexpress/velo9/member/dto/MemberThumbnailDTO.java
  src/main/java/teamexpress/velo9/member/security/oauth/CustomOAuth2UserService.java
  src/main/java/teamexpress/velo9/member/security/oauth/OAuthAttributes.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostAccess.java
  src/main/java/teamexpress/velo9/post/domain/PostStatus.java
  src/main/java/teamexpress/velo9/post/domain/PostThumbnailType.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepository.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/dto/PostSaveDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/java/teamexpress/velo9/post/service/PostThumbnailFileService.java
  src/main/resources/application.properties
Labels: feature, 회원가입

#36 글 수정을 더한 글 작성
  src/main/java/teamexpress/velo9/member/api/MemberThumbnailFileUploader.java
  src/main/java/teamexpress/velo9/member/dto/MemberThumbnailDTO.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/domain/PostRepository.java
  src/main/java/teamexpress/velo9/post/domain/PostTag.java
  src/main/java/teamexpress/velo9/post/domain/PostTagRepository.java
  src/main/java/teamexpress/velo9/post/dto/PostSaveDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/java/teamexpress/velo9/post/service/TagService.java
  src/main/resources/application.properties
Labels: feature, 글쓰기

#37 회원정보 수정-기본 구현
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/controller/MemberDTO.java
  src/main/java/teamexpress/velo9/member/controller/MemberEditDTO.java
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/member/domain/Role.java
  src/main/java/teamexpress/velo9/member/security/handler/AjaxAuthenticationSuccessHandler.java
  src/main/java/teamexpress/velo9/member/security/oauth/CustomOAuth2UserService.java
  src/main/java/teamexpress/velo9/member/service/MemberService.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/test/java/teamexpress/velo9/member/service/MemberServiceTest.java
Labels: feature, 회원 정보 수정

#41 feat: 좋아요 테이블(클래스) 구현
  src/main/java/teamexpress/velo9/member/domain/Look.java
  src/main/java/teamexpress/velo9/member/domain/Love.java
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepository.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/resources/application.properties
Labels: feature, 읽기 목록(좋아요/최근)

#40 Post, Seires 리팩토링 및 테스트 구현
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/dto/PostSeriesDTO.java
  src/main/java/teamexpress/velo9/post/dto/SeriesDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/test/java/teamexpress/velo9/InitDb.java
  src/test/java/teamexpress/velo9/post/domain/PostRepositoryTest.java
  src/test/java/teamexpress/velo9/post/domain/SeriesRepositoryTest.java
  src/test/resources/application.properties
Labels: refactoring, 개인블로그메인/시리즈, 개인블로그메인/글

#45 회원 비밀번호 변경 및 탈퇴 구현
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/member/service/MemberService.java
  src/test/java/teamexpress/velo9/member/service/MemberServiceTest.java
Labels: feature, 회원 정보 수정

#46 DTO 추가
  src/main/java/teamexpress/velo9/member/dto/MemberDTO.java
  src/main/java/teamexpress/velo9/member/dto/MemberEditDTO.java
  src/main/java/teamexpress/velo9/member/dto/PasswordDTO.java
Labels: chore

#47 Member profile
  .gitignore
  src/main/java/teamexpress/velo9/member/api/MemberThumbnailFileUploader.java
  src/main/java/teamexpress/velo9/member/controller/MemberThumbnailController.java
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/member/dto/MemberThumbnailDTO.java
  src/main/java/teamexpress/velo9/member/security/handler/AjaxAuthenticationFailureHandler.java
  src/main/java/teamexpress/velo9/member/service/MemberService.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepository.java
  src/main/java/teamexpress/velo9/post/service/PostThumbnailFileService.java
  src/main/java/teamexpress/velo9/post/service/TagService.java
Labels: feature, 회원가입

#49 feat: 특정 회원의 temporary 상태로 저장된 posts 조회 API
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepository.java
  src/main/java/teamexpress/velo9/post/dto/TempSavedPostDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/resources/application.properties
  src/test/java/teamexpress/velo9/InitDb.java
  src/test/java/teamexpress/velo9/member/service/MemberServiceTest.java
  src/test/java/teamexpress/velo9/post/domain/PostRepositoryTest.java
  src/test/java/teamexpress/velo9/post/service/PostServiceTest.java
  src/test/resources/application.properties
Labels: feature, 임시저장 글 목록

#50 feat: love, look 동작 시 count 로직 추가
  src/main/java/teamexpress/velo9/member/domain/LoveRepository.java
  src/main/java/teamexpress/velo9/post/domain/PostRepository.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
Labels: feature, 읽기 목록(좋아요/최근)

#51 메인페이지 구현 (태그검색 X)
  src/main/java/teamexpress/velo9/member/dto/MemberMainDTO.java
  src/main/java/teamexpress/velo9/member/dto/MemberThumbnailDTO.java
  src/main/java/teamexpress/velo9/post/controller/MainController.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/domain/TagRepository.java
  src/main/java/teamexpress/velo9/post/domain/TagRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/TagRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/dto/PostMainDTO.java
  src/main/java/teamexpress/velo9/post/dto/SearchCondition.java
  src/main/java/teamexpress/velo9/post/dto/SeriesDTO.java
  src/main/java/teamexpress/velo9/post/dto/TagDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/test/java/teamexpress/velo9/post/domain/PostRepositoryTest.java
Labels: feature, 메인 화면

#55 feat: 특정 회원이 최근 읽은 글을 모두 조회하는 API
  src/main/java/teamexpress/velo9/InitDb.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/dto/LookPostDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/test/java/teamexpress/velo9/InitDb.java
  src/test/java/teamexpress/velo9/post/service/PostServiceTest.java
Labels: feature, 읽기 목록(좋아요/최근)

#53 refactor: 메인페이지 통합 및 리팩토링
  src/main/java/teamexpress/velo9/post/controller/MainController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
Labels: 메인 화면, refactoring

#57 feat: 태그 검색 구현
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/domain/PostTag.java
Labels: feature, 메인 화면

#58 feat: memberId와 seriesName 조건이 일치하는 모든 Post를 조회하는 API
  src/main/java/teamexpress/velo9/InitDb.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/dto/SeriesPostSummaryDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
Labels: feature, 툭정 시리즈 글 목록

#54 임시저장
  src/main/java/teamexpress/velo9/InitDb.java
  src/main/java/teamexpress/velo9/member/domain/LookRepository.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/domain/PostRepository.java
  src/main/java/teamexpress/velo9/post/domain/TemporaryPost.java
  src/main/java/teamexpress/velo9/post/domain/TemporaryPostRepository.java
  src/main/java/teamexpress/velo9/post/dto/PostSaveDTO.java
  src/main/java/teamexpress/velo9/post/dto/TemporaryPostReadDTO.java
  src/main/java/teamexpress/velo9/post/dto/TemporaryPostWriteDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
Labels: feature, 글쓰기

#56 feat: 아이디,비밀번호 찾기 1차 구현
  src/main/java/teamexpress/velo9/member/controller/MailController.java
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/domain/MemberRepository.java
  src/main/java/teamexpress/velo9/member/dto/FindInfoDTO.java
  src/main/java/teamexpress/velo9/member/dto/MemberNewPwDTO.java
  src/main/java/teamexpress/velo9/member/service/MailHandler.java
  src/main/java/teamexpress/velo9/member/service/MailService.java
  src/main/java/teamexpress/velo9/member/service/MemberService.java
Labels: feature, Id/Pw 찾기

#59 feat: 글 상세 페이지 1차 구현
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/dto/PostMemberDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostMemberThumbnailDTO.java
  src/main/java/teamexpress/velo9/post/dto/ReadDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/test/java/teamexpress/velo9/post/domain/PostRepositoryTest.java
Labels: feature, 글 상세페이지

#60 feat: 첫 소셜 로그인 멤버 -> 회원가입 구현
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/member/dto/SocialSignupDTO.java
  src/main/java/teamexpress/velo9/member/security/oauth/CustomOAuth2UserService.java
  src/main/java/teamexpress/velo9/member/security/oauth/OAuthAttributes.java
  src/main/java/teamexpress/velo9/member/service/MemberService.java
Labels: feature, 회원가입

#62 refactor
  src/main/java/teamexpress/velo9/member/api/MemberThumbnailFileUploader.java
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/controller/MemberDTO.java
  src/main/java/teamexpress/velo9/member/controller/MemberEditDTO.java
  src/main/java/teamexpress/velo9/member/controller/MemberThumbnailController.java
  src/main/java/teamexpress/velo9/member/domain/MemberRepository.java
  src/main/java/teamexpress/velo9/member/domain/MemberThumbnailRepository.java
  src/main/java/teamexpress/velo9/member/dto/MemberNewPwDTO.java
  src/main/java/teamexpress/velo9/member/dto/PasswordDTO.java
  src/main/java/teamexpress/velo9/member/security/common/AjaxLoginAuthenticationEntryPoint.java
  src/main/java/teamexpress/velo9/member/security/configure/AjaxLoginConfigurer.java
  src/main/java/teamexpress/velo9/member/security/filter/AjaxLoginProcessingFilter.java
  src/main/java/teamexpress/velo9/member/security/handler/AjaxAccessDeniedHandler.java
  src/main/java/teamexpress/velo9/member/security/handler/AjaxAuthenticationFailureHandler.java
  src/main/java/teamexpress/velo9/member/security/handler/AjaxAuthenticationSuccessHandler.java
  src/main/java/teamexpress/velo9/member/security/oauth/CustomOAuth2UserService.java
  src/main/java/teamexpress/velo9/member/security/oauth/SessionConst.java
  src/main/java/teamexpress/velo9/member/security/provider/AjaxAuthenticationProvider.java
  src/main/java/teamexpress/velo9/member/service/MailService.java
  src/main/java/teamexpress/velo9/member/service/MemberService.java
  src/main/java/teamexpress/velo9/post/controller/MainController.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/controller/PostThumbnailFileController.java
  src/main/java/teamexpress/velo9/post/domain/PostTag.java
  src/main/java/teamexpress/velo9/post/domain/PostTagRepository.java
  src/main/java/teamexpress/velo9/post/domain/PostThumbnailRepository.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/domain/TagRepository.java
  src/main/java/teamexpress/velo9/post/dto/PostMainDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostThumbnailDTO.java
  src/main/java/teamexpress/velo9/post/dto/SearchCondition.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/java/teamexpress/velo9/post/service/PostThumbnailFileService.java
  src/main/java/teamexpress/velo9/post/service/SeriesService.java
  src/main/java/teamexpress/velo9/post/service/TagService.java
  src/main/java/teamexpress/velo9/post/task/PostThumbnailTask.java
Labels: refactoring

#63 refactor: memberId를session에서 찾아 사용하는 방식에서, Front에서 전달받아 사용하는 방식으로 리팩토링
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
Labels: refactoring

#65 Refactor2
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/controller/MemberThumbnailController.java
  src/main/java/teamexpress/velo9/member/domain/MemberRepository.java
  src/main/java/teamexpress/velo9/member/dto/MemberDTO.java
  src/main/java/teamexpress/velo9/member/service/MemberService.java
  src/main/java/teamexpress/velo9/post/controller/MainController.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
Labels: refactoring

#66 Api docs test
  src/main/java/teamexpress/velo9/InitDb.java
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/dto/ReadDTO.java
  src/main/java/teamexpress/velo9/post/dto/TempSavedPostDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/test/java/teamexpress/velo9/InitDb.java
  src/test/java/teamexpress/velo9/member/controller/MemberControllerTest.java
  src/test/java/teamexpress/velo9/member/service/MemberServiceTest.java
  src/test/java/teamexpress/velo9/post/controller/PostControllerTest.java
  src/test/java/teamexpress/velo9/post/domain/PostRepositoryTest.java
  src/test/java/teamexpress/velo9/post/domain/SeriesRepositoryTest.java
  src/test/java/teamexpress/velo9/post/service/PostServiceTest.java
Labels: Test
