Repository team-express/velo9, pull requests merged in 2022-04, with the labels that each got.

#68 feat: 잘못된 구현 수정 및 리팩토링
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/controller/SeriesController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
Labels: refactoring

#69 feat: 태그 선택 구현
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/dto/PostReadDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostSummaryDTO.java
  src/main/java/teamexpress/velo9/post/dto/TempSavedPostDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
Labels: feature

#70 컨트롤러 테스트 완성
  src/docs/asciidoc/PostAPI.adoc
  src/docs/asciidoc/api.adoc
  src/docs/asciidoc/etc.adoc
  src/docs/asciidoc/etcAPI.adoc
  src/main/java/teamexpress/velo9/post/controller/MainController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/dto/ReadDTO.java
  src/main/java/teamexpress/velo9/post/dto/SeriesReadDTO.java
  src/test/java/teamexpress/velo9/InitDb.java
  src/test/java/teamexpress/velo9/post/controller/MainControllerTest.java
  src/test/java/teamexpress/velo9/post/controller/PostControllerTest.java
  src/test/java/teamexpress/velo9/post/controller/SeriesControllerTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: Test

#71 feat: 인증번호 검증 로직 구현
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/dto/NumberDTO.java
  src/main/java/teamexpress/velo9/member/dto/RandomNumber.java
  src/main/java/teamexpress/velo9/member/security/oauth/SessionConst.java
Labels: feature

#72 컨트롤러 테스트 및 문서화 완성
  src/docs/asciidoc/MemberAPI.adoc
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/member/dto/MemberEditDTO.java
  src/test/java/teamexpress/velo9/InitDb.java
  src/test/java/teamexpress/velo9/member/controller/MemberControllerTest.java
Labels: Test

#74 Query refactor
  src/main/java/teamexpress/velo9/member/domain/LookRepository.java
  src/main/java/teamexpress/velo9/member/domain/LookRepositoryCustom.java
  src/main/java/teamexpress/velo9/member/domain/LookRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/domain/PostRepository.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/domain/PostTagQueryRepository.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepository.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/dto/PostReadDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostSaveDTO.java
  src/main/java/teamexpress/velo9/post/dto/ReadDTO.java
  src/main/java/teamexpress/velo9/post/dto/SeriesPostSummaryDTO.java
  src/main/java/teamexpress/velo9/post/dto/TagDTO.java
  src/main/java/teamexpress/velo9/post/dto/TransferDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/java/teamexpress/velo9/post/service/SeriesService.java
  src/test/java/teamexpress/velo9/post/controller/PostControllerTest.java
Labels: refactoring

#73 Fix
  src/docs/asciidoc/MemberAPI.adoc
  src/main/java/teamexpress/velo9/common/task/MemberThumbnailTask.java
  src/main/java/teamexpress/velo9/common/task/PostThumbnailTask.java
  src/main/java/teamexpress/velo9/member/domain/LookRepository.java
  src/main/java/teamexpress/velo9/member/domain/LoveRepository.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepository.java
  src/main/java/teamexpress/velo9/post/dto/SeriesDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/java/teamexpress/velo9/post/service/SeriesService.java
  src/main/java/teamexpress/velo9/post/service/TagService.java
  src/test/java/teamexpress/velo9/InitDb.java
  src/test/java/teamexpress/velo9/member/controller/MemberControllerTest.java
  src/test/java/teamexpress/velo9/post/controller/PostControllerTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: bug

#77 Refactor post
  src/main/java/teamexpress/velo9/common/domain/PostResult.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepository.java
  src/main/java/teamexpress/velo9/post/domain/TagRepository.java
  src/main/java/teamexpress/velo9/post/dto/PostSaveDTO.java
  src/main/java/teamexpress/velo9/post/dto/SeriesReadDTO.java
  src/main/java/teamexpress/velo9/post/dto/TagDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/java/teamexpress/velo9/post/service/SeriesService.java
  src/main/java/teamexpress/velo9/post/service/TagService.java
  src/test/java/teamexpress/velo9/post/controller/PostControllerTest.java
Labels: refactoring

#78 refactor
  src/main/java/teamexpress/velo9/member/service/MemberService.java
Labels: refactoring

#76 Api convention
  BOOT-INF/classes/static/docs/MemberAPI.html
  BOOT-INF/classes/static/docs/PostAPI.html
  BOOT-INF/classes/static/docs/api.html
  BOOT-INF/classes/static/docs/etcAPI.html
  build.gradle
  src/docs/asciidoc/MemberAPI.adoc
  src/docs/asciidoc/PostAPI.adoc
  src/main/java/teamexpress/velo9/common/dto/ThumbnailResponseDTO.java
  src/main/java/teamexpress/velo9/common/exception/Velo9ExceptionHandler.java
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/controller/MemberThumbnailController.java
  src/main/java/teamexpress/velo9/member/dto/MemberDTO.java
  src/main/java/teamexpress/velo9/member/dto/MemberMainDTO.java
  src/main/java/teamexpress/velo9/member/dto/MemberNewPwDTO.java
  src/main/java/teamexpress/velo9/member/dto/MemberThumbnailDTO.java
  src/main/java/teamexpress/velo9/member/service/MemberService.java
  src/main/java/teamexpress/velo9/post/api/PostThumbnailFileUploader.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/controller/PostThumbnailController.java
  src/main/java/teamexpress/velo9/post/domain/PostTagQueryRepository.java
  src/main/java/teamexpress/velo9/post/domain/PostTagRepository.java
  src/main/java/teamexpress/velo9/post/dto/PostMainDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostMemberDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostMemberThumbnailDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostReadDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostSaveDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostSummaryDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostThumbnailDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostWriteDTO.java
  src/main/java/teamexpress/velo9/post/dto/SeriesPostSummaryDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/java/teamexpress/velo9/post/service/PostThumbnailFileService.java
  src/test/java/teamexpress/velo9/member/controller/MemberControllerTest.java
  src/test/java/teamexpress/velo9/post/controller/PostControllerTest.java
  static/docs/api.html
  static/docs/etc.html
Labels: chore

#82 Api convention
  build.gradle
  src/docs/asciidoc/MemberAPI.adoc
  src/docs/asciidoc/PostAPI.adoc
  src/docs/asciidoc/etcAPI.adoc
  src/main/java/teamexpress/velo9/common/controller/BaseController.java
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/controller/MemberThumbnailController.java
  src/main/java/teamexpress/velo9/member/dto/MemberHeaderDTO.java
  src/main/java/teamexpress/velo9/member/service/MemberService.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/controller/SeriesController.java
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/dto/LoveDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostSaveDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostWriteDTO.java
  src/main/java/teamexpress/velo9/post/dto/SeriesAddDTO.java
  src/main/java/teamexpress/velo9/post/dto/TemporaryPostWriteDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/java/teamexpress/velo9/post/service/SeriesService.java
  src/test/java/teamexpress/velo9/member/controller/MemberControllerTest.java
  src/test/java/teamexpress/velo9/post/controller/PostControllerTest.java
  src/test/java/teamexpress/velo9/post/controller/SeriesControllerTest.java
Labels: feature

#87 Fix : post 수정 시 introduce, access null줄때의 처리
  src/main/java/teamexpress/velo9/member/domain/Member.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/dto/PostSaveDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/test/java/teamexpress/velo9/member/controller/MemberControllerTest.java
  src/test/java/teamexpress/velo9/post/controller/PostControllerTest.java
Labels: 글쓰기, bug

#88 Fix write get
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/dto/PostReadDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
Labels: 글쓰기, bug

#89 Refactor
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/service/MailService.java
  src/main/java/teamexpress/velo9/member/service/MemberService.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/domain/SeriesRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/java/teamexpress/velo9/post/service/TagService.java
Labels: refactoring

#91 테스트 폼 단일화 + /write 테스트 1차구현
  src/main/java/teamexpress/velo9/post/dto/PostSaveDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostWriteDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/test/java/teamexpress/velo9/InitDb.java
  src/test/java/teamexpress/velo9/member/controller/docs/MemberControllerTest.java
  src/test/java/teamexpress/velo9/post/controller/PostControllerTest.java
  src/test/java/teamexpress/velo9/post/controller/docs/MainControllerTest.java
  src/test/java/teamexpress/velo9/post/controller/docs/PostControllerTest.java
  src/test/java/teamexpress/velo9/post/controller/docs/SeriesControllerTest.java
Labels: 글쓰기, Test

#94 Oauth2
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/security/configure/SecurityConfig.java
  src/main/java/teamexpress/velo9/member/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/teamexpress/velo9/member/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/teamexpress/velo9/member/security/oauth/CustomOAuth2UserService.java
  src/main/java/teamexpress/velo9/member/security/oauth/OAuthAttributes.java
  src/main/java/teamexpress/velo9/member/security/test/OAuth2SuccessHandler.java
  src/main/resources/application-oauth.properties
Labels: feature

#95 test: writeGet, writePost 테스트 완성
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/dto/PostSaveDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/main/java/teamexpress/velo9/post/service/TagService.java
  src/test/java/teamexpress/velo9/InitDb.java
  src/test/java/teamexpress/velo9/post/controller/PostControllerTest.java
Labels: 글쓰기, bug, Test

#96 Oauth
  src/main/java/teamexpress/velo9/member/security/configure/SecurityConfig.java
  src/main/java/teamexpress/velo9/member/security/oauth/OAuth2SuccessHandler.java
Labels: refactoring

#98 feat: 쿼리 최적화
  src/main/java/teamexpress/velo9/member/domain/LookRepository.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/Post.java
  src/main/java/teamexpress/velo9/post/domain/PostRepository.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustom.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/domain/PostTagRepository.java
  src/main/java/teamexpress/velo9/post/dto/PostReadDTO.java
  src/main/java/teamexpress/velo9/post/dto/SeriesDTO.java
  src/main/java/teamexpress/velo9/post/dto/SeriesPostSummaryDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
Labels: feature

#104 비밀번호 찾기 -> 이메일 전송 메서드 추가
  src/main/java/teamexpress/velo9/member/controller/MemberController.java
  src/main/java/teamexpress/velo9/member/service/MemberService.java
  src/test/java/teamexpress/velo9/member/controller/docs/MemberControllerTest.java
Labels: bug

#110 bug: 버그 수정(tag가 전부 조회되는 현상)
  src/main/java/teamexpress/velo9/post/domain/PostTagRepository.java
  src/main/java/teamexpress/velo9/post/dto/PostReadDTO.java
  src/main/java/teamexpress/velo9/post/dto/SeriesPostSummaryDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
Labels: bug

#111 bug: postTag 조인 문제 해결
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/domain/PostTagRepository.java
  src/main/java/teamexpress/velo9/post/dto/PostReadDTO.java
  src/main/java/teamexpress/velo9/post/dto/SeriesPostSummaryDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
Labels: bug

#113 아카이브 수정
  src/main/java/teamexpress/velo9/common/exception/Velo9ExceptionHandler.java
  src/main/java/teamexpress/velo9/post/controller/PostController.java
  src/main/java/teamexpress/velo9/post/domain/PostRepositoryCustomImpl.java
  src/main/java/teamexpress/velo9/post/dto/LookPostDTO.java
  src/main/java/teamexpress/velo9/post/dto/PostArchiveDTO.java
  src/main/java/teamexpress/velo9/post/service/PostService.java
  src/test/java/teamexpress/velo9/InitDb.java
  src/test/java/teamexpress/velo9/member/controller/docs/MemberControllerTest.java
Labels: feature, 읽기 목록(좋아요/최근)

#117 chore: asciidoctor 삭제
  build.gradle
Labels: release
